services:
  test:
    build: .
    ports:
      - 7388:8888
    volumes: 
      - ./:/workspace/code/
      - /mnt/:/workspace/data/ # optional: modify this file to mount your own data path
    tty: true 
    stdin_open: true
    shm_size: 96GB
    deploy:
      resources:
        reservations:
          cpus: '96'
          memory: 96G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]